### ISSUE TITLE
Not able to bring in Moralis library.

### ISSUE THREAD

**Issue by happyeric77** [happyeric77/mobile-dapp-boilerplate#1]
This react-native expo project is inspired by [this project](https://github.com/clxyder/walletconnect-expo-example) by which I get my app work with walletconnect.
In addition to it, I would like to extend the feature with moralis solution, I understand that Moralis team has [official react-native boilerplate](https://github.com/ethereum-boilerplate/ethereum-react-native-boilerplate)  but it [requires react-native-cli with bare bone](https://forum.moralis.io/t/help-react-native-unable-to-resolve-module-crypto-could-not-be-found/6033/9?u=happyeric77) project, which is not what I want to implement. I would like to implement it with expo go as it is done with walletconnect.
However, it turns out that several issues occur while tyring to bring in moralis library.See [here](https://forum.moralis.io/t/ethereum-react-native-boilerplate-questions/4511/124?u=happyeric77).  

It will be appreciated if anybody who has already got around it (moralis + expo go) could share some hints with me so that I can carry on.

**Comment by gen02-dev** [comment]
After cloning the app and switching to the 4.Moralis_provider branch, I just deleted package-lock.json and yarn.lock. Then I changed the react-native version to "react-native": "0.63.3" in the package.json file. Then I run yarn install. After it finished downloading node_modules, I ran expo start and it launched the app succesfully. Try deleting node_modules and repeat the same process.

**Comment by happyeric77** [comment]
Thanks, Man!!! you really save my day.
I just downgraded the react-native version from 0.64.3 to 0.63.3. Then I now can get into the app even it shows some warnings below :
```
Logs for your project will appear below. Press Ctrl+C to exit.
Warning: Invalid version react-native@0.63.3 for expo sdkVersion 44.0.0. Use react-native@0.64.3
iOS Bundling complete 7495ms
iOS Running app on iPhone4EricSE

Warning: The provided value 'ms-stream' is not a valid 'responseType'.

Warning: The provided value 'moz-chunked-arraybuffer' is not a valid 'responseType'.
```
I am not sure if it will be a matter afterward, but at least now I can call moralis function with no problem.

**Comment by happyeric77** [comment]
@gen02-dev 
I am facing the next issue to integrate wallectConnect's "connector" object with Moralis authenticate function.
I understand that moralis authenticate function requires the certain format to be passed in and team has modified the walletConnect's source code to make it suited. So, I replaced the default wallectconnect lib with the "./frontend/WalletConnect.
The I followed the sample code "./frontend/Components/CryptoAuth.js ( https://github.com/gen02-dev/ethereum-react-native-cli-boilerplate) passing the "connector" object into authenticate(). But it turns out the error
```
Non ethereum enabled browser
```
It will be appreciated if you could give me a hint that where did I miss out.
You could also have a look at [my repo](https://github.com/happyeric77/mobile-dapp-boilerplate/tree/5.Moralis_WalletConnect) branch#5 (5.Moralis_WalletConnect) if you have time. The authenticate() call is in ./screens/main.tsx 

Many thanks!

**Comment by gen02-dev** [comment]
@happyeric77 I created a brach named `fix-walletconnect`. When you checkout this branch, make sure to delete `node_modules`. Then run `yarn install` again and run the app with `yarn ios`. Below is the screenshot after I believe I fixed it:

<img width="359" alt="Screen Shot 2022-01-19 at 3 24 01 PM" src="https://user-images.githubusercontent.com/61220663/150083465-484b3c69-786f-4e7e-a7c2-abf5f27e15de.png">

**Comment by happyeric77** [comment]
@gen02-dev Thanks so much! I just have a try and it works! AMAZING AGAIN!
I also briefly checked the diff but I could not really see what is the cause of this issue. I realized:

The App is wrapped one more layer by MoralisDappProvider
Some npm packages have been changed.
It will be appreciated if you do not mind letting me know what is the key taking effect to fix it.
